export * from './framework-score.interface';
export * from './framework-control.interface';
export * from './framework-resource.interface';
export * from './scan-summary.interface';
export * from './framework-overtime.interface';
export * from './overtime-cord.interface';
export * from './overtime-chart-data.interface';
export * from './cluster-overtime-dto.interface'
export * from './cluster-overtime.interface';
export * from './vulnerability.interface';
export * from './vulnerability-period.interface';
export * from './vulnerability-overtime';
export * from './vulnerability-sumsummary.interface'
